export const initialState = {  
  onlogin: false,
  coronaRecord: null,
  weatherRecord: null,
  navbarItems: null,
  selectedStory: null,
  user: null,
  news: null,
  stories: null,
  internationalStories: null,
  nationalStories: null,
  biographicalStories: null,
  sportsStories: null,
  showbizStories: null,
  englishStories: null,
};
